package com.vendsy.bartsy.venue.model;

import org.json.JSONException;
import org.json.JSONObject;

import com.j256.ormlite.field.DatabaseField;
import com.vendsy.bartsy.venue.R;

/**
 * @author Seenu
 * 
 *         A MenuDrink object we are creating and persisting to the database.
 */
public class Item {
	// id is generated by the database and set on the object automatically
	@DatabaseField(id = true)
	private String itemId = null;
	@DatabaseField
	private String title = null;
	@DatabaseField
	private String image = null;
	@DatabaseField
	private String description = null;
	@DatabaseField
	private String optionsDescription = null;
	@DatabaseField
	private String price = null;
	@DatabaseField
	private String price_special = null;
	@DatabaseField
	private String venueId = null;

	@DatabaseField(canBeNull = true, foreign = true, foreignAutoRefresh = true, columnName = "section_id")
	private Section section;
	

	public Item() {
	}

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String drinkId) {
		this.itemId = drinkId;
	}
	
	public Item(JSONObject object) {

		try {
			if (object.has("itemName"))
				this.title = object.getString("itemName");
			if (object.has("name"))
				this.title = object.getString("name");
			
			if (object.has("description"))
				this.description = object.getString("description");

			if (object.has("options_description"))
				this.optionsDescription = object.getString("options_description");
			
			if (object.has("price"))
				this.price = object.getString("price");
			if (object.has("basePrice"))
				this.price = object.getString("basePrice");
			
			if (object.has("id"))
				this.itemId = object.getString("id");

		} catch (JSONException e) {
			e.printStackTrace();
		}

		// For now always use the same image for the drink
		this.image = Integer.toString(R.drawable.drink);
	} 

	public boolean has(String field) {
		return !(field == null || field.equals(""));
	}
	
	/**
	 * @return the venueId
	 */
	public String getVenueId() {
		return venueId;
	}

	/**
	 * @param venueId the venueId to set
	 */
	public void setVenueId(String venueId) {
		this.venueId = venueId;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the image
	 */
	public String getImage() {
		return image;
	}

	/**
	 * @param image
	 *            the image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the description
	 */
	public String getOptionsDescription() {
		return optionsDescription;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setOptionsDescription(String description) {
		this.optionsDescription = description;
	}

	/**
	 * @return the price
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * @param price
	 *            the price to set
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * @return the price_special
	 */
	public String getPrice_special() {
		return price_special;
	}

	/**
	 * @param price_special
	 *            the price_special to set
	 */
	public void setPrice_special(String price_special) {
		this.price_special = price_special;
	}

	/**
	 * @return the section
	 */
	public Section getSection() {
		return section;
	}

	/**
	 * @param section
	 *            the section to set
	 */
	public void setSection(Section section) {
		this.section = section;
	}

}
